repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/rotten/blue.git
    rev: "0.6.1"
    hooks:
    - id: blue
      args: [ --line-length=120 ]
  - repo: local
    hooks:
    - id: commit-prefix
      name: validate commit pre fix
      language: pygrep
      entry: '^(?!fix: |feat: |ci: |docs: |refactor: |test: |infra: |chore: )[a-zA-Z0-9_.]'
      args: [--multiline]
      stages: [commit-msg]
