repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/rotten/blue.git
    rev: "0.6.1"
    hooks:
    - id: blue
      args: [ --line-length=120 ]
